### ISSUE TITLE
Data and resourse for History page (documentation)

### ISSUE THREAD

**Issue by HarshKumarraghav** [HarshKumarraghav/periodically_webapp#30]
### Describe the Issue

Data and resources on the History page like:
  

> history of the periodic table 
>  about Mendeleev(father of the periodic table)
>  Mendeleev periodic table
>  how many periodic tables are made

**Comment by janmesh799** [comment]
hey harsh,
i think i can do this

**Comment by janmesh799** [comment]
I can do both. But I can't be sure if data and resources would be as good as you want

**Comment by HarshKumarraghav** [comment]
ya, that's why just wait for today we will create the mock-up design where you can add any type of data.  And when we have real data then we just replace dummy data with real data.

**Comment by HarshKumarraghav** [comment]
And I will let you know that I have created the issue for UI.

**Comment by Apurv428** [comment]
I am interested in working on making the documentation. Please assign this issue to me @HarshKumarraghav

**Comment by HarshKumarraghav** [comment]
It is not creating the UI it's just providing the data for the history page.

**Comment by Apurv428** [comment]
Okay

**Comment by HarshKumarraghav** [comment]
okay, @Apurv428 I'm assigning this issue to you. You can connect with me on LinkedIn so that we can discuss how It will be done.

**Comment by Sonal-Maurya** [comment]
Hey I want to contribute to this issue

**Comment by HarshKumarraghav** [comment]
> Hey I want to contribute to this issue

ok, I'm assigning this issue to you.

**Comment by HarshKumarraghav** [comment]
@janmesh799 I have created the issue for coding the UI for the history page If you are still interested in it.

**Comment by HarshKumarraghav** [comment]
> Hey I want to contribute to this issue

h1 @Sonal-Maurya If you want to contribute to the documentation I can assign it to you.

**Comment by TechGeek3** [comment]
Hey, I want to contribute for the documentation of history page.

**Comment by HarshKumarraghav** [comment]
Ok, I am assigning this task to you @TechGeek3

**Comment by TechGeek3** [comment]
![image](https://user-images.githubusercontent.com/84609623/196055308-b0002361-c349-4e9b-9ec5-7987a3383a8b.png)
This is how the documentation should be right?

**Comment by HarshKumarraghav** [comment]
Ya but some images would be favourable.

**Comment by TechGeek3** [comment]
Ya sure I'll add them.

**Comment by TechGeek3** [comment]
Where should I add the images used in documentation? public folder?
